// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyShopApi.Data;

#nullable disable

namespace MyShopApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522072332_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("MyShopApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Áo",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Áo thun cotton cao cấp",
                            ImageUrl = "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=300&q=80",
                            Name = "Áo Thun Trắng",
                            Price = 150000m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Quần",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Quần jeans thời trang",
                            ImageUrl = "https://images.unsplash.com/photo-1542272604-787c3835535d?w=300&q=80",
                            Name = "Quần Jeans Xanh",
                            Price = 350000m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Giày",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Giày sneaker năng động",
                            ImageUrl = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=300&q=80",
                            Name = "Giày Sneaker",
                            Price = 500000m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Phụ kiện",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Túi xách thời trang",
                            ImageUrl = "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=300&q=80",
                            Name = "Túi Xách",
                            Price = 200000m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Áo",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Áo khoác denim phong cách",
                            ImageUrl = "https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=300&q=80",
                            Name = "Áo Khoác Denim",
                            Price = 450000m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Quần",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Quần shorts thoải mái",
                            ImageUrl = "https://images.unsplash.com/photo-1565084888279-aca607ecce0c?w=300&q=80",
                            Name = "Quần Shorts",
                            Price = 180000m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Phụ kiện",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mũ lưỡi trai thời trang",
                            ImageUrl = "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=300&q=80",
                            Name = "Mũ Lưỡi Trai",
                            Price = 120000m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Giày",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Giày sandal mùa hè",
                            ImageUrl = "https://images.unsplash.com/photo-1603487742131-4160ec999306?w=300&q=80",
                            Name = "Giày Sandal",
                            Price = 280000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
